### ISSUE TITLE
InputTextField NoSuchMethodError Crash

### ISSUE THREAD

**Issue by Gil2599** [maxkeppeler/sheets-compose-dialogs#32] opened 2023-03-02 07:02 UTC
Seems like using InputTextField as one of the input options for Input Dialog throws NoSuchMethodError. 

```java.lang.NoSuchMethodError: No static method TextField(Ljava/lang/String;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Modifier;ZZLandroidx/compose/ui/text/TextStyle;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;ZLandroidx/compose/ui/text/input/VisualTransformation;Landroidx/compose/foundation/text/KeyboardOptions;Landroidx/compose/foundation/text/KeyboardActions;ZILandroidx/compose/foundation/interaction/MutableInteractionSource;Landroidx/compose/ui/graphics/Shape;Landroidx/compose/material3/TextFieldColors;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/material3/TextFieldKt; or its super classes (declaration of 'androidx.compose.material3.TextFieldKt' appears in /data/app/~~hWNpS5NQIa0cv5wDFM3ITw==/com.<package-name>-IlNA4GFNg4kloexJLTKSXw==/base.apk)```

Current versions:
Compose: 1.3.1
Compose Compiler: 1.4.3
Kotlin: 1.8.10
Dialogs Library: 1.1.0

**Comment by maxkeppeler** [comment] 2023-03-13 11:32
Sheets-Compose-Dialogs is currently using Compose 1.3.0. Try downgrading to the equal version 1.3.0 until Sheets-Compose-Dialogs is updated.

**Comment by Gil2599** [comment] 2023-03-15 07:32
Error seems to be happening on Compose version 1.3.0 also.

**Comment by maxkeppeler** [comment] 2023-03-16 13:43
The current version supports: 1.3.0 Compose & Compiler | 1.7.10 Kotlin
1.1.1 will use: 
   ```
    const val KOTLIN = "1.8.10"

    const val COMPOSE_BOM = "2023.01.00"
    const val COMPOSE = "1.3.3"
    const val COMPOSE_COMPILER = "1.4.3"
```

**Comment by maxkeppeler** [comment] 2023-03-24 09:48
Unfortunately, I don't know where to get started. Or what else could be relevant for this error. I was certain the correct compose versions would fix this issue, as it is common with those kinds of errors. I can't reproduce it in my apps or in the sample. Did you double-check that all the version (Kotlin, Compose and Build Gradle) are the same or compatible as in 1.1.1?

**Comment by Gil2599** [comment] 2023-03-24 20:48
I am using the same Compose BOM version as in 1.1.1 with Kotlin 1.8.10. Everything should be compatible. Only difference I could find is that I am using a higher Compose Navigation version, but I am not sure why that would cause this issue.

**Comment by maxkeppeler** [comment] 2023-03-27 11:38
It's highly unlikely in my opinion that the different compose navigation version would cause this. Did you try to Invalidate Caches etc.? I have unfortunately no further ideas, what could cause that as you are also the first one experiencing it so far.

**Comment by PeterKastner** [comment] 2023-04-07 12:37
Hi, I was just experiencing the same crash when using InputTextField as one of the input options for Input Dialog  

@Gil2599 Are you by any chance using a specific version of 

`androidx.compose.material3:material3` or
`androidx.compose.material3:material3-window-size-class`

meaning _**not**_ specified by the Compose BOM?

What fixed it for me was reverting back to not declare the specific version of material3 - `androidx.compose.material3:material3:1.1.0-beta01` in my `build.gradle` file.

Am using
 `composeBom = platform("androidx.compose:compose-bom:2023.01.00")`
`kotlinCompilerExtensionVersion '1.4.3'` and
` id 'org.jetbrains.kotlin.android' version '1.8.10' apply false`
currently to work around the crash.

Regards, happy easter and let me know what you think.

**Comment by russellbanks** [comment] 2023-05-03 22:30
https://github.com/JetBrains/compose-multiplatform/issues/2673#issuecomment-1406347828

As @PeterKastner said this seems to occur when using a pre-release Material3 version because it breaks backwards compatibility.

**Comment by russellbanks** [comment] 2023-05-10 23:52
Material3 has reached 1.1.0. This should hopefully be fixed once sheets updates to that too.

**Comment by maxkeppeler** [comment] 2023-05-21 10:38
I will update the BOM dependency to 2023.04.01 which includes the Material3 1.1.0 dependency.

**Closed** 2023-05-21 10:49 UTC
Labels: help wanted
